// @flow
import keys from './keys';

export default {
  APP_NAME: 'NumValidate',
  APP_DESCRIPTION: 'NumValidate description.',
  DOCS: 'Docs',
  CONFIRM: 'Confirm',
  DASHBOARD: 'Dashboard',
  CLOSE: 'Close',
  CANCEL: 'Cancel',
  LOGOUT: 'Logout',
  LOGIN: 'Login',
  SNACKBAR_TEXT: 'There has been an error processing your request, please try again later.',
  HOME_SIGNUP_NOW_AUTHENTICATED: 'Open your dashboard',
  HOME_SIGNUP_NOW_UNAUTHENTICATED: 'Signup now',
  DASHBOARD_ERROR_TITLE: 'Unauthorized',
  DASHBOARD_ERROR_MESSAGE_GENERIC: 'You are not authorized to access the dashboard.',
  DASHBOARD_ERROR_MESSAGE_VERIFY_EMAIL: 'Please verify your email before logging in.',
  DASHBOARD_ERROR_BUTTON: 'Login and try again',
  API_TOKEN_TITLE: 'API token',
  API_TOKEN_SUBTITLE: 'Your API token allows you to authenticate with NumValidate APIs.',
  API_TOKEN_REVEAL_BUTTON: 'Reveal token',
  API_TOKEN_GENERATE_BUTTON: 'Generate a new API token',
  API_TOKEN_TABLE_HEADER_NAME: 'Name',
  API_TOKEN_TABLE_HEADER_TOKEN: 'Token',
  API_TOKEN_TABLE_HEADER_UPDATED: 'Last update',
  API_TOKEN_GENERATOR_INPUT_REQUIRED: 'Required',
  API_TOKEN_GENERATOR_INPUT_PLACEHOLDER: 'Assign a meaningful name to the token',
  API_TOKEN_GENERATOR_BUTTON_TEXT: 'Confirm',
  API_TOKEN_GENERATOR_MODAL_TITLE: 'New API token',
  SUBSCRIPTION_TITLE: 'Your subscription',
  SUBSCRIPTION_SUBTITLE: 'You can change your subscription type anytime.',
  SUBSCRIPTION_TABLE_HEADER_SUBSCRIPTION: 'Subscription',
  SUBSCRIPTION_SELECT_BUTTON: 'Select',
  SUBSCRIPTION_CURRENT_PLAN: 'Your current plan',
  PAYMENT_INFO_TITLE: 'Your payment info',
  PAYMENT_INFO_SUBTITLE: 'Your card details for the monthly NumValidate billing.',
  PAYMENT_INFO_UPDATE_BUTTON: 'Update payment info',
  PAYMENT_INFO_TABLE_HEADER_CARD: 'Card details',
  PAYMENT_INFO_TABLE_HEADER_UPDATED: 'Last update',
  PAYMENT_INFO_FREE_PLAN_AMOUNT: `€0/month`,
  PAYMENT_INFO_FREE_PLAN_DESCRIPTION: `${keys.RATE_LIMIT_FOR_FREE_USER_REQUESTS ||
    ''} daily API requests.`,
  PAYMENT_INFO_PRO_PLAN_AMOUNT: `€${keys.STRIPE_PRO_PLAN_AMOUNT / 100 || ''}/month`,
  PAYMENT_INFO_PRO_PLAN_DESCRIPTION: `${keys.RATE_LIMIT_FOR_PRO_USER_REQUESTS ||
    ''} daily API requests. Email Support.`,
  PAYMENT_INFO_FREE_MODAL_TITLE: 'Subscription change',
  PAYMENT_INFO_FREE_MODAL_TEXT: 'Do you confirm the change to the free plan?',
  PAYMENT_INFO_PRO_MODAL_TITLE: 'Subscription change',
  PAYMENT_INFO_PRO_MODAL_TEXT:
    "Do you confirm the change to the pro plan?\nYou'll be asked to enter your credit card detail.",
  TEST:
    'NumValidates is powered by <a href={"https://github.com/googlei18n/libphonenumber"}>Google LibPhoneNumber</a>, a phon number formatting and parsing library released by Google, originally developed for (and currently used in) Google\'s Androi mobile phone operating system, which uses a several rigorous rules for parsing, formatting, and validating phone numbers for all countries/regions of the world.',
};
